server:
  port: 8081

spring:
  application:
    name: rest-service
  datasource:
    url: jdbc:postgresql://localhost:5432/outbox
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
