server:
  port: 8081

spring:
  application:
    name: rest-service
  datasource:
    url: jdbc:postgresql://localhost:5432/outbox
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: W3C
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
